[build]
  base = "personal portfolio/portfolio project"
  publish = "personal portfolio/portfolio project/build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
